name: Terraform Apply

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AZ_CLIENT_ID: ${{secrets.AZ_CLIENT_ID}
      AZ_CLIENT_SECRET: ${{secrets.AZ_CLIENT_SECRET}}
      AZ_SUBS_ID: ${{secrets.AZ_SUBS_ID}}
      AZ_TENANT_ID: ${{secrets.AZ_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

